[program:donation_download]
command=/venv/main/bin/python /workspace/donation-replacement/download.py
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/donation-replacement/download.log
redirect_stderr=true
stdout_logfile_maxbytes=20MB
