[program:donation_model]
command=/bin/bash /workspace/donation-replacement/serve.sh
autostart=false
autorestart=unexpected
startsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/donation-replacement/server.log
redirect_stderr=true
stdout_logfile_maxbytes=40MB

[program:donation_replacements]
command=/venv/main/bin/python /workspace/donation-replacement/run.py
directory=/workspace/donation-replacement
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/donation-replacement/run.log
redirect_stderr=true
stdout_logfile_maxbytes=20MB
